#!/bin/bash

set -ueo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(cat <&0)

timestamp=$(jq --raw-output '.version.timestamp // empty' <<< "${payload}")

if [[ -z "${timestamp}" ]]; then
  echo '[]' >&3
else
    jq --null-input \
        --arg "timestamp" "${timestamp}" \
        '[ { timestamp: $timestamp } ]' \
        >&3
fi
