#!/bin/bash

set -ueo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(cat <&0)

timestamp=$(jq --raw-output '.version.timestamp // "none"' <<< "${payload}")

jq --null-input \
    --arg "timestamp" "${timestamp}" \
    '{ version: { timestamp: $timestamp } }' \
    >&3
