#!/bin/bash

set -e

cd "${1}"

exec 3>&1
exec 1>&2
set +x
# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"

disable="$(jq -r '.source.disable' < "${payload}")"
if [[ "$disable" == "true" ]]
then
    echo "$timestamp" >&3
    exit 0
fi

webhook_url="$(jq -r '.source.url' < "${payload}")"
allow_insecure="$(jq -r '.source.insecure // "false"' < "${payload}")"
raw_ca_certs=$(jq -r '.source.ca_certs // []' < $payload)

text_file="$(jq -r '.params.text_file // ""' < "${payload}")"
text="$(jq -r '(.params.text // "${TEXT_FILE_CONTENT}")' < "${payload}")"
username="$(jq '(.params.username // null)' < "${payload}")"
icon_url="$(jq '(.params.icon_url // null)' < "${payload}")"
icon_emoji="$(jq '(.params.icon_emoji // null)' < "${payload}")"
link_names="$(jq -r '(.params.link_names // false)' < "${payload}")"

channels="$(jq -r '(.params.channel // null)' < "${payload}")"
channel_file="$(jq -r '(.params.channel_file // null)' < "${payload}")"
attachments_file="$(jq -r '.params.attachments_file // ""' < "${payload}")"
attachments=$(jq -r '(.params.attachments // null)' < $payload)

debug="$(jq -r '.params.debug // "false"' < "${payload}")"
show_metadata="$(jq -r '.params.metadata // "false"' < "${payload}")"
show_payload="$(jq -r '.params.payload_in_metadata // "false"' < "${payload}")"
silent="$(jq -r '.params.silent // "false"' < "${payload}")"
always_notify="$(jq -r '.params.always_notify // "false"' < "${payload}")"
redact_hook="$(jq -r '.params.redact_hook_url // "true"' < "${payload}")"

proxy="$(jq -r '.source.proxy // "null"' < "${payload}")"
proxy_https_tunnel="$(jq -r '.source.proxy_https_tunnel // "false"' < "${payload}")"


cert_count="$(echo $raw_ca_certs | jq -r '. | length')"
if [[ ${cert_count} -gt 0 ]]
then
  cert_dir="/usr/local/share/ca-certificates/"
  mkdir -p "$cert_dir"
  for i in $(seq 0 $(expr "$cert_count" - 1));
  do
    echo $raw_ca_certs | jq -r .[$i].cert >> "${cert_dir}/ca-cert-$(echo $raw_ca_certs | jq -r .[$i].domain).crt"
  done
  update-ca-certificates
fi

export TEXT_FILE_CONTENT=""
[[ -n "${text_file}" && ! -f "${text_file}" ]] && text_file=""
[[ -n "${text_file}" && -f "${text_file}" ]] && TEXT_FILE_CONTENT="$(cat "${text_file}")"

ATTACHMENTS_FILE_CONTENT=""
[[ -n "${attachments_file}" && -f "${attachments_file}" ]] && ATTACHMENTS_FILE_CONTENT="$(cat "${attachments_file}")"
if [[ "${attachments}" == "null" && -n $ATTACHMENTS_FILE_CONTENT ]]; then
  attachments=$ATTACHMENTS_FILE_CONTENT
fi

attachments=$(echo "$attachments" | envsubst)

[[ -n "${channel_file}" && -f "${channel_file}" ]] && channels="${channels} $(cat "${channel_file}")"

for channel in ${channels}
do

debug_info=""
metadata=""
body=""


if [[ "$allow_insecure" == "true" ]]
then
    CURL_OPTION="${CURL_OPTION} -k"
fi

if [[ "$proxy" != "null" ]]
then
    CURL_OPTION="${CURL_OPTION} --proxy ${proxy}"
fi

if [[ "$proxy_https_tunnel" == "true" ]]
then
    CURL_OPTION="${CURL_OPTION} --proxytunnel"
fi

if [[ "$always_notify" == "true" || -n "$TEXT_FILE_CONTENT" || -z "$text_file" ]]
then
  if [[ "${attachments}" == "null" ]]
  then
    TEXT_FILE_CONTENT="${TEXT_FILE_CONTENT:-_(no notification provided)_}"
  fi

  text_interpolated=$(echo -n "$text" |envsubst)

  if [[ -z "${text_interpolated}" ]]
  then
    text_interpolated="_(missing notification text)_"
    [[ -n "${attachments}" ]] && text_interpolated="null"
  else
    text_interpolated="$(echo "${text_interpolated}" | jq -R -s .)"
  fi

  [[ "${username}"   != "null" ]] && username="$(eval "printf ${username}" | jq -R -s .)"
  [[ "${icon_url}"   != "null" ]] && icon_url="$(eval "printf ${icon_url}" | jq -R -s .)"
  [[ "${icon_emoji}" != "null" ]] && icon_emoji="$(eval "printf ${icon_emoji}" | jq -R -s .)"
  [[ "${channel}"    != "null" ]] && channel=\"${channel}\" && channel="$(eval "printf ${channel}" | jq -R -s .)"

  body="$(cat <<EOF
{
  "text": ${text_interpolated},
  "username": ${username},
  "link_names": ${link_names},
  "icon_url": ${icon_url},
  "icon_emoji": ${icon_emoji},
  "channel": ${channel},
  "attachments": ${attachments}
}
EOF
  )"

  compact_body="$(echo "${body}" | jq -c '.')"

  if [[ "$debug" == "true" ]]
  then
    debug_info="$(cat <<EOF
{
  "webhook_url": "${webhook_url}",
  "body": ${body}
}
EOF
)"
  elif [[ "$silent" == "true" ]]
  then
    echo "Using silent output"
    curl -s --data-urlencode "payload=${compact_body}" ${CURL_OPTION} "${webhook_url}"
  elif [[ ${redact_hook} == "true" ]]
  then
    url_path="$(echo ${webhook_url} | sed -e "s/https\{0,1\}:\/\/[^\/]*\(\/[^?&#]*\).*/\1/")"
    curl -v --data-urlencode "payload=${compact_body}" ${CURL_OPTION} "${webhook_url}" 2>&1 | sed -e "s#${url_path}#***WEBHOOK URL REDACTED***#g"
  else
    curl -v --data-urlencode "payload=${compact_body}" ${CURL_OPTION} "${webhook_url}" | sed -e "s#${url_path}#***WEBHOOK URL REDACTED***#g"
  fi
else
  text_interplated="$(echo "" | jq -R -s .)"
fi

done

if [[ "$show_metadata" == "true" ]]
then
  redacted_webhook_url=$(echo "${webhook_url}" | sed -e 's#/\([^/\.]\{2\}\)[^/.]\{5,\}\([^/.]\{2\}\)#/\1…\2#g' | jq -R .)
  escaped_text_file="$(echo $text_file | jq -R -s . )"
  if [[ ${redact_hook} == "true" ]]
  then
    escaped_payload="$(cat $payload | jq -rcM ".source.url = \"***REDACTED***\"" | jq -R -s . )"
  else
    escaped_payload="$(cat $payload | jq -rcM ".source.url = \"***REDACTED***\"" | jq -R -s . )"
  fi

  escaped_content="$(echo $TEXT_FILE_CONTENT | jq -R -s . )"
  text_file_exists="No" && [[ -n "$text_file" ]] && [[ -f "$text_file" ]] && text_file_exists=Yes
  metadata="$(cat <<EOF
{
  "metadata": [
    {"name": "url",               "value": ${redacted_webhook_url}},
    {"name": "channel",           "value": "${channels}"          },
    {"name": "username",          "value": ${username}            },
    {"name": "text",              "value": ${text_interpolated}   },
    {"name": "text_file",         "value": $( echo "$text_file"         | jq -R . ) },
    {"name": "text_file_exists",  "value": $( echo "$text_file_exists"  | jq -R . ) },
    {"name": "text_file_content", "value": $( echo "$TEXT_FILE_CONTENT" | jq -R -s . ) }
  ]
}
EOF
  )"
  if [[ "${show_payload}" == "true" ]]
  then
    metadata="$( echo ${metadata} | jq -r ".metadata += [{name: \"payload\", value: $escaped_payload}]")"
  fi

fi

echo "$timestamp $metadata $debug_info " | jq -s add  >&3
