name: Trigger Concourse 'develop' resource
on: [ push, workflow_dispatch ]
jobs:
  trigger-resource-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger resource check
        uses: gstackio/trigger-concourse-resource-check-action@v1
        with:
          concourse-url:           https://ci.gstack.io
          concourse-team:          gk-plat-devs
          concourse-pipeline:      slack-notification-resource
          concourse-resource:      develop
          concourse-webhook-token: ${{ secrets.GK_CONCOURSE_WEBHOOK_TOKEN }}
